### ISSUE TITLE
Current version of Constant Contact api

### ISSUE THREAD

**Issue by jiminps** [katzwebservices/Constant-Contact-WordPress-Plugin#11]
This is a wonderful plug-in.  However, a 'Submit' button or a 'Send' button isn't showing up on the resultant form when placed via a widget.  Here's the website (in development):

http://d33.376.myftpupload.com

Scroll to the bottom and you'll see your plug-in in Footer column 1.  

Thank you,

Jiminps

**Comment by drmcclain** [comment]
One of a kind plugin, thanks. I changed my list names in Constant Contact but it's not reflected in the Form Designer, any way to refresh or force this to change?
