### ISSUE TITLE
Can't Load Events Page in WordPress

### ISSUE THREAD

**Issue by patdumond** [katzwebservices/Constant-Contact-WordPress-Plugin#18]
I just noticed this because I was alerted to a change in the PHP Error Log -- I'm not sure which one of my clients was trying to access the Events page via the Constant Contact plugin last night, they did not report an error to me. 

When I reviewed the PHP Error Log (attached) I found that the errors being reported were in the CC plugin. I went to the site and tried to access the Events page and got a screen full of error messages (also attached).  

Thanks in advance. Any help would be appreciated. 

Patricia Dumond

![20141211 - screenshot php error log](https://cloud.githubusercontent.com/assets/9320495/5396820/23e0d898-8123-11e4-825d-f0490e0a175c.png)
![20141211 - screenshot events page error messages - part i](https://cloud.githubusercontent.com/assets/9320495/5396819/23df3f4c-8123-11e4-8f3f-c70ebadb19d6.png)
![20141211 - screenshot events page error messages - part ii](https://cloud.githubusercontent.com/assets/9320495/5396821/23e1ab10-8123-11e4-8e46-4afc0325fbf5.png)

**Comment by zackkatz** [comment]
Fixed in 3.1.8. Thanks for reporting!
