### ISSUE TITLE
Insert/Edit link no longer working

### ISSUE THREAD

**Issue by SamWilliamson** [katzwebservices/Constant-Contact-WordPress-Plugin#21]
I am using version 3.1.6 of this plugin, 4.1 of Wordpress, and Michael Hyatt's Get Noticed Theme.

Today I tried to make a post with normal links to another site (wikipedia) and the Insert/Edit Link button no longer worked. (I entered the link via free form text)

I reinstalled wordpress. Didn't work. I began disabling plugins. When I disabled the Constant Contact Plugin for Wordpress, all of a sudden I could edit links again. I re-enabled Constant Contact plugin, and I couldn't edit links. I again disabled Constant Contact Plugin, and links could be edited again.

Something isn't working in the newer Constant Contact Plugin.

Help!

**Comment by zackkatz** [comment]
Try disabling EventSpot in the plugin settings.

**Comment by SamWilliamson** [comment]
That did it. Thanks.
