### ISSUE TITLE
Widget Error for Eventspot

### ISSUE THREAD

**Issue by bluetopmarketing** [katzwebservices/Constant-Contact-WordPress-Plugin#33]
I'm receiving this error on pages where I'm using the Constant Contact Events widget. But it really only happens the first time you go to the pages. You go back and the correct info is there. Please assist. Thanks, Stephanie

Error:
Catchable fatal error: Argument 1 passed to KWS_V1API::getEventDetails() must be an instance of Event, instance of __PHP_Incomplete_Class given, called in /home/content/p3pnexwpnas02_data02/32/2777832/html/wp-content/plugins/constant-contact-api/lib/eventspot/shortcode.php on line 26 and defined in/home/content/p3pnexwpnas02_data02/32/2777832/html/wp-content/plugins/constant-contact-api/lib/eventspot/class.kwsv1api.php on line 24

**Comment by forgueam** [comment]
We are seeing the same error. It appears to be related to GoDaddy caching. Here is another case of it occurring:  [https://wordpress.org/support/topic/issue-with-site#post-6729428](url)
