### ISSUE TITLE
Fatal Error on Activation

### ISSUE THREAD

**Issue by rmzindorf** [katzwebservices/Constant-Contact-WordPress-Plugin#38]
Wordpress 4.5 - running PHP  5.5

Throws error after plugin activation, cuts off access to wp-admin/
`Fatal error: Class 'Ctct\Auth\CtctOAuth2' not found in /home/rfnadmin/public_html/wp-content/plugins/Constant-Contact-WordPress-Plugin-master/classes/class.kwsoauth2.php on line 21
`
Have to manually remove to files from cpanel, and upon return plugin alert message reads...
`The plugin Constant-Contact-WordPress-Plugin-master/constant-contact-api.php has been deactivated due to an error: Plugin file does not exist.`

**Comment by zackkatz** [comment]
The plugin requires you build it. Downloading directly from GitHub won't work. 

Please download from here: https://katz.co/wp-content/uploads/2016/04/constant-contact-api.zip
